### ISSUE TITLE
Change Keyboard Shortcut and Add Custom App

### ISSUE THREAD

**Issue by kholisrag** [MirServer/egmde-confined-desktop#2]
sir @AlanGriffiths 
can you show me where is the source code to change the keyboard shorcut and add custom app? for this egmde snap app?

**Comment by AlanGriffiths** [comment]
The egmde source is here: https://github.com/AlanGriffiths/egmde - the text is hard-coded in the wallpaper and launcher files, a PR making that configurable would be gratefully received.

The snap source is here: https://github.com/MirServer/egmde-confined-desktop - that’s where the applications are pulled in from the archive. You can use that as a starting point for your own snap with your customised set of applications.

**Comment by kholisrag** [comment]
@AlanGriffiths this egmde snap is already out of the box for xwayland? gtk app (electronjs)?

**Comment by AlanGriffiths** [comment]
> this egmde snap is already out of the box for xwayland? gtk app (electronjs)?

No

**Comment by kholisrag** [comment]
> > this egmde snap is already out of the box for xwayland? gtk app (electronjs)?
> 
> No

If I want to use mir-kiosk-apps ([https://github.com/MirServer/mir-kiosk-apps](https://github.com/MirServer/mir-kiosk-apps)), It's out of the box for electron apps using xwayland or not?

**Comment by AlanGriffiths** [comment]
1. This is off topic for egmde-confined-desktop.
2. Your last question is easily answered by looking at mir-kiosk-apps.
3. This might help you help yourself: https://tutorials.ubuntu.com/tutorial/electron-kiosk#0

Closing the issue.
